### ISSUE TITLE
Connection Side-bar issues...

### ISSUE THREAD

**Issue by adamretter** [evolvedbinary/fusion-studio-extension#18]
Okay, I am now able to get the Electron and Browser apps to run :-)

A few issues still remain from #17:
1. Clicking the `File` menu, and then `Connect...` does nothing.
2. You have to click `View` menu, and then `Pebble Connections` to get the side-bar to show.
    1. Could we have this open by default and above the Files menu in the sidebar?
3. If I create a connection and click on it, but the eXist server is not available or does not have the API installed I get nothing, on the console I see:
```
root ERROR caught: { code: 0, data: [ {} ] }
```
We should instead add an error popup dialog or something telling the user "Sorry, unable to connect to server at `http://localhost:8080`. Invalid response from the server".

**Comment by joewiz** [comment]
Also, when switching to a new or recent Workspace, any connections that have been set up are lost and must be re-created. Steps to reproduce:

1. Start Pebble (I'm using the Mac .app).
2. From Files tab, select Open Workspace.
3. Select a directory to use as the workspace root.
4. From Connections tab, select New Connection. Complete the dialog and select Connect.
5. Select File > Close Workspace.
6. Select File > Open Recent Workspace...
7. Notice that the Connections tab has no connections.

**Comment by ccheraa** [comment]
ClickUp tag: cu-7crwtm[in progress]

**Comment by adamretter** [comment]
Confirmed - 

1. Whether using the default workspace or creating a new workspace - the result is the same
2. Create a new connection
3. Open the connection
4. Click Save or Save All
5. Quit the application
6. Reopen the application
7. You will see that the connections have been forgotten
8. Also it does not open any previous workspace that was open when you Quit the application

**Comment by ccheraa** [comment]
Already fixed

**Comment by ccheraa** [comment]
Already fixed
