### ISSUE TITLE
Running electron-app directly shows incorrect title and icon

### ISSUE THREAD

**Issue by adamretter** [evolvedbinary/fusion-studio-extension#184]
When launching the electron-app directly, the title and icon of the application are incorrect. 
<img width="141" alt="Screenshot 2020-07-24 at 12 31 31" src="https://user-images.githubusercontent.com/1264057/88383235-720fe480-cdaa-11ea-9b21-26a24b590283.png">

**Comment by duncdrum** [comment]
as discussed today this seems to have been fixed, please reopen if the wrong icon still appears inside a specific environment
