### ISSUE TITLE
Properties dialog is missing resource name

### ISSUE THREAD

**Issue by adamretter** [evolvedbinary/fusion-studio-extension#188]
When inspecting the properties of a resource in the Properties dialog, it is now missing the resource name.

<img width="1180" alt="Screenshot 2020-07-24 at 13 07 01" src="https://user-images.githubusercontent.com/1264057/88385561-daf95b80-cdae-11ea-9ad3-7fa6e6eebf07.png">

We need to add Cypress tests for this also.

**Comment by ccheraa** [comment]
This issue is fixed
