### ISSUE TITLE
XAR is not cached by .travis or AppVeyor

### ISSUE THREAD

**Issue by adamretter** [evolvedbinary/fusion-studio-extension#211]
For the eXist-db test builds, we should download the XAR to a location which is cached by Travis and AppVeyor, therefore avoiding the need to download it repeatedly.

**Comment by duncdrum** [comment]
Travis and appveyor are out, we can revisit caching on Circle once  the tests are more reliable and once we have addressed https://github.com/evolvedbinary/fusion-studio-api/issues/56
