### ISSUE TITLE
Drop Python 2 support

### ISSUE THREAD

**Issue by duncdrum** [evolvedbinary/fusion-studio-extension#350]
Time to say goodbye

**Comment by adamretter** [comment]
@duncdrum It's important to us to support as broad a spectrum of platforms as possible at runtime. If the dependency is only need at build-time, then we can indeed upgrade. If it is needed at runtime, it has to stay.

**Comment by duncdrum** [comment]
It seems that Theia is increasingly incompatible with `Py2`, while i don't think there is a run-time dependency at all, even if there is. I'd say to ditch it its EOL, and we want to be able to stay with the upstread dev flow. Ditching it also saves us build minutes. @ccheraa what do you think?

**Comment by duncdrum** [comment]
@ccheraa what do you say, from what i can see Python 2 is no longer required for building Fusion Studio, since theia moved on, and I don't see any runtime dependencies?

**Comment by ccheraa** [comment]
Python is used at build time by `node-gyp`, and they don't officially support `python 3`, from their repo:
> `python` (`v2.7` recommended, `v3.x.x` is not supported)

**Comment by duncdrum** [comment]
So, at [runtime](https://github.com/eclipse-theia/theia/blob/master/doc/Developing.md#prerequisites) python doesn't seem to be needed at all. 

The only place that i can see mentioning `py2` is [here](https://github.com/theia-ide/yangster-electron) along with `node8`; last commit: `2018`. `node8` and `py2` are EOL. [Theia itself](https://github.com/eclipse-theia/theia/runs/2179917636) no longer builds and tests with these. The yangster Ci with node8 on macOS is failing. We know that node-gyp on macOS works with py3, since we actually made that pull-request. 

I basically think that the readme is outdated, and we should ditch py2, if there is a PR to yangser to bring its dependencies in line with theia's let's do that.

**Comment by adamretter** [comment]
Before we make any changes I would really like to get the CI back in-place. That will help us confirm the Python changes. We previously had jobs running for both Python 2 and 3 - https://github.com/evolvedbinary/fusion-studio-extension/blob/master/.travis.yml#L26

So I guess once we have Circle in place we could revisit this.

**Comment by adamretter** [comment]
We now have CircleCI in place
