### ISSUE TITLE
using typescript for cypress tests

### ISSUE THREAD

**Issue by duncdrum** [evolvedbinary/fusion-studio-extension#404]
Since we're rewriting anyway should we switch to typescript for the tests? its officially supported [docs](https://docs.cypress.io/guides/tooling/typescript-support#Install-TypeScript)

**Comment by adamretter** [comment]
If we can use TypeScript through out that would be preferred, but we should bot rewrite old tests for the sake of it. New tests or old tests that have to be fixed can be done in TypeScript

**Comment by duncdrum** [comment]
I foresee 0 bandwidth for this in the near future, we should reassess this again in the future.
